//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stumps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stumps.BaseResources", typeof(BaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule is already initialized..
        /// </summary>
        internal static string BodyRuleAlreadyInitializedError {
            get {
                return ResourceManager.GetString("BodyRuleAlreadyInitializedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://*:{0}/.
        /// </summary>
        internal static string HttpServerPattern {
            get {
                return ResourceManager.GetString("HttpServerPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://*:{0}/.
        /// </summary>
        internal static string HttpsServerPattern {
            get {
                return ResourceManager.GetString("HttpsServerPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI for the remote HTTP server is invalid..
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not:.
        /// </summary>
        internal static string NotPattern {
            get {
                return ResourceManager.GetString("NotPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regex:.
        /// </summary>
        internal static string RegExPattern {
            get {
                return ResourceManager.GetString("RegExPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be changed while the server is running..
        /// </summary>
        internal static string ServerIsRunning {
            get {
                return ResourceManager.GetString("ServerIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stump with the specified identifier already exists..
        /// </summary>
        internal static string StumpAlreadyExistsError {
            get {
                return ResourceManager.GetString("StumpAlreadyExistsError", resourceCulture);
            }
        }
    }
}
