//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stumps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stumps.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is already running..
        /// </summary>
        internal static string ApplicationRunning {
            get {
                return ResourceManager.GetString("ApplicationRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stumps
        ///
        ///Usage: stumps [/i] [/u]
        ///
        ////i   Installs Stumps as a service
        ////u   Removes the Stumps service.
        ///.
        /// </summary>
        internal static string HelpInformation {
            get {
                return ResourceManager.GetString("HelpInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /i.
        /// </summary>
        internal static string InstallCommandLineArg {
            get {
                return ResourceManager.GetString("InstallCommandLineArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete..
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed..
        /// </summary>
        internal static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Stumps....
        /// </summary>
        internal static string InstallStarting {
            get {
                return ResourceManager.GetString("InstallStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StumpsService.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        internal static string ShutdownComplete {
            get {
                return ResourceManager.GetString("ShutdownComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Stumps....
        /// </summary>
        internal static string ShutdownStarting {
            get {
                return ResourceManager.GetString("ShutdownStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started..
        /// </summary>
        internal static string StartupComplete {
            get {
                return ResourceManager.GetString("StartupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Stumps....
        /// </summary>
        internal static string StartupStarting {
            get {
                return ResourceManager.GetString("StartupStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /u.
        /// </summary>
        internal static string UninstallCommandLineArg {
            get {
                return ResourceManager.GetString("UninstallCommandLineArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall complete..
        /// </summary>
        internal static string UninstallComplete {
            get {
                return ResourceManager.GetString("UninstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall failed..
        /// </summary>
        internal static string UninstallFailed {
            get {
                return ResourceManager.GetString("UninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling Stumps....
        /// </summary>
        internal static string UninstallStarting {
            get {
                return ResourceManager.GetString("UninstallStarting", resourceCulture);
            }
        }
    }
}
