//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("1.0.0+ChrisWa-20140106T145356Z")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyTitle("Stumps.Engine")]
[assembly: System.Reflection.AssemblyDescription("Stumps Runtime Engine")]
[assembly: System.Runtime.InteropServices.Guid("3a65988b-7beb-4d38-b944-4390b9ea8c7f")]


