//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("1.0.0+ChrisWa-20140106T145356Z")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyTitle("Stumps.Startup")]
[assembly: System.Reflection.AssemblyDescription("Stumps Application")]
[assembly: System.Runtime.InteropServices.Guid("ae9efa41-4aaa-4568-9611-7a9b03d13c47")]


